//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace AISRS.Common.Data {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("AISTOCK_STOCK_TWO_PIN_V_DATA")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class AISTOCK_STOCK_TWO_PIN_V_DATA : global::System.Data.DataSet {
        
        private AISTOCK_STOCK_TWO_PIN_VDataTable tableAISTOCK_STOCK_TWO_PIN_V;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public AISTOCK_STOCK_TWO_PIN_V_DATA() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected AISTOCK_STOCK_TWO_PIN_V_DATA(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["AISTOCK_STOCK_TWO_PIN_V"] != null)) {
                    base.Tables.Add(new AISTOCK_STOCK_TWO_PIN_VDataTable(ds.Tables["AISTOCK_STOCK_TWO_PIN_V"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public AISTOCK_STOCK_TWO_PIN_VDataTable AISTOCK_STOCK_TWO_PIN_V {
            get {
                return this.tableAISTOCK_STOCK_TWO_PIN_V;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            AISTOCK_STOCK_TWO_PIN_V_DATA cln = ((AISTOCK_STOCK_TWO_PIN_V_DATA)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["AISTOCK_STOCK_TWO_PIN_V"] != null)) {
                    base.Tables.Add(new AISTOCK_STOCK_TWO_PIN_VDataTable(ds.Tables["AISTOCK_STOCK_TWO_PIN_V"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableAISTOCK_STOCK_TWO_PIN_V = ((AISTOCK_STOCK_TWO_PIN_VDataTable)(base.Tables["AISTOCK_STOCK_TWO_PIN_V"]));
            if ((initTable == true)) {
                if ((this.tableAISTOCK_STOCK_TWO_PIN_V != null)) {
                    this.tableAISTOCK_STOCK_TWO_PIN_V.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "AISTOCK_STOCK_TWO_PIN_V_DATA";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/AISTOCK_STOCK_TWO_PIN_V_DATA.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableAISTOCK_STOCK_TWO_PIN_V = new AISTOCK_STOCK_TWO_PIN_VDataTable();
            base.Tables.Add(this.tableAISTOCK_STOCK_TWO_PIN_V);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeAISTOCK_STOCK_TWO_PIN_V() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            AISTOCK_STOCK_TWO_PIN_V_DATA ds = new AISTOCK_STOCK_TWO_PIN_V_DATA();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void AISTOCK_STOCK_TWO_PIN_VRowChangeEventHandler(object sender, AISTOCK_STOCK_TWO_PIN_VRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class AISTOCK_STOCK_TWO_PIN_VDataTable : global::System.Data.TypedTableBase<AISTOCK_STOCK_TWO_PIN_VRow> {
            
            private global::System.Data.DataColumn columnSTOCK_CODE;
            
            private global::System.Data.DataColumn columnSTOCK_NAME;
            
            private global::System.Data.DataColumn columnYESTERDAY;
            
            private global::System.Data.DataColumn columnYESTERDAY_BEGIN;
            
            private global::System.Data.DataColumn columnYESTERDAY_END;
            
            private global::System.Data.DataColumn columnYESTERDAY_MIN_PRICE;
            
            private global::System.Data.DataColumn columnTODAY;
            
            private global::System.Data.DataColumn columnTODAY_BEGIN;
            
            private global::System.Data.DataColumn columnTODAY_END;
            
            private global::System.Data.DataColumn columnTODAY_MIN_PRICE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VDataTable() {
                this.TableName = "AISTOCK_STOCK_TWO_PIN_V";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AISTOCK_STOCK_TWO_PIN_VDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected AISTOCK_STOCK_TWO_PIN_VDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STOCK_CODEColumn {
                get {
                    return this.columnSTOCK_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn STOCK_NAMEColumn {
                get {
                    return this.columnSTOCK_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YESTERDAYColumn {
                get {
                    return this.columnYESTERDAY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YESTERDAY_BEGINColumn {
                get {
                    return this.columnYESTERDAY_BEGIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YESTERDAY_ENDColumn {
                get {
                    return this.columnYESTERDAY_END;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn YESTERDAY_MIN_PRICEColumn {
                get {
                    return this.columnYESTERDAY_MIN_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TODAYColumn {
                get {
                    return this.columnTODAY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TODAY_BEGINColumn {
                get {
                    return this.columnTODAY_BEGIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TODAY_ENDColumn {
                get {
                    return this.columnTODAY_END;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TODAY_MIN_PRICEColumn {
                get {
                    return this.columnTODAY_MIN_PRICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VRow this[int index] {
                get {
                    return ((AISTOCK_STOCK_TWO_PIN_VRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AISTOCK_STOCK_TWO_PIN_VRowChangeEventHandler AISTOCK_STOCK_TWO_PIN_VRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AISTOCK_STOCK_TWO_PIN_VRowChangeEventHandler AISTOCK_STOCK_TWO_PIN_VRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AISTOCK_STOCK_TWO_PIN_VRowChangeEventHandler AISTOCK_STOCK_TWO_PIN_VRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event AISTOCK_STOCK_TWO_PIN_VRowChangeEventHandler AISTOCK_STOCK_TWO_PIN_VRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddAISTOCK_STOCK_TWO_PIN_VRow(AISTOCK_STOCK_TWO_PIN_VRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VRow AddAISTOCK_STOCK_TWO_PIN_VRow(string STOCK_CODE, string STOCK_NAME, string YESTERDAY, decimal YESTERDAY_BEGIN, decimal YESTERDAY_END, decimal YESTERDAY_MIN_PRICE, string TODAY, decimal TODAY_BEGIN, decimal TODAY_END, decimal TODAY_MIN_PRICE) {
                AISTOCK_STOCK_TWO_PIN_VRow rowAISTOCK_STOCK_TWO_PIN_VRow = ((AISTOCK_STOCK_TWO_PIN_VRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        STOCK_CODE,
                        STOCK_NAME,
                        YESTERDAY,
                        YESTERDAY_BEGIN,
                        YESTERDAY_END,
                        YESTERDAY_MIN_PRICE,
                        TODAY,
                        TODAY_BEGIN,
                        TODAY_END,
                        TODAY_MIN_PRICE};
                rowAISTOCK_STOCK_TWO_PIN_VRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowAISTOCK_STOCK_TWO_PIN_VRow);
                return rowAISTOCK_STOCK_TWO_PIN_VRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                AISTOCK_STOCK_TWO_PIN_VDataTable cln = ((AISTOCK_STOCK_TWO_PIN_VDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new AISTOCK_STOCK_TWO_PIN_VDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnSTOCK_CODE = base.Columns["STOCK_CODE"];
                this.columnSTOCK_NAME = base.Columns["STOCK_NAME"];
                this.columnYESTERDAY = base.Columns["YESTERDAY"];
                this.columnYESTERDAY_BEGIN = base.Columns["YESTERDAY_BEGIN"];
                this.columnYESTERDAY_END = base.Columns["YESTERDAY_END"];
                this.columnYESTERDAY_MIN_PRICE = base.Columns["YESTERDAY_MIN_PRICE"];
                this.columnTODAY = base.Columns["TODAY"];
                this.columnTODAY_BEGIN = base.Columns["TODAY_BEGIN"];
                this.columnTODAY_END = base.Columns["TODAY_END"];
                this.columnTODAY_MIN_PRICE = base.Columns["TODAY_MIN_PRICE"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnSTOCK_CODE = new global::System.Data.DataColumn("STOCK_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTOCK_CODE);
                this.columnSTOCK_NAME = new global::System.Data.DataColumn("STOCK_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTOCK_NAME);
                this.columnYESTERDAY = new global::System.Data.DataColumn("YESTERDAY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYESTERDAY);
                this.columnYESTERDAY_BEGIN = new global::System.Data.DataColumn("YESTERDAY_BEGIN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYESTERDAY_BEGIN);
                this.columnYESTERDAY_END = new global::System.Data.DataColumn("YESTERDAY_END", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYESTERDAY_END);
                this.columnYESTERDAY_MIN_PRICE = new global::System.Data.DataColumn("YESTERDAY_MIN_PRICE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnYESTERDAY_MIN_PRICE);
                this.columnTODAY = new global::System.Data.DataColumn("TODAY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTODAY);
                this.columnTODAY_BEGIN = new global::System.Data.DataColumn("TODAY_BEGIN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTODAY_BEGIN);
                this.columnTODAY_END = new global::System.Data.DataColumn("TODAY_END", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTODAY_END);
                this.columnTODAY_MIN_PRICE = new global::System.Data.DataColumn("TODAY_MIN_PRICE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTODAY_MIN_PRICE);
                this.columnSTOCK_CODE.MaxLength = 20;
                this.columnSTOCK_NAME.MaxLength = 100;
                this.columnYESTERDAY.MaxLength = 20;
                this.columnTODAY.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VRow NewAISTOCK_STOCK_TWO_PIN_VRow() {
                return ((AISTOCK_STOCK_TWO_PIN_VRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new AISTOCK_STOCK_TWO_PIN_VRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(AISTOCK_STOCK_TWO_PIN_VRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.AISTOCK_STOCK_TWO_PIN_VRowChanged != null)) {
                    this.AISTOCK_STOCK_TWO_PIN_VRowChanged(this, new AISTOCK_STOCK_TWO_PIN_VRowChangeEvent(((AISTOCK_STOCK_TWO_PIN_VRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.AISTOCK_STOCK_TWO_PIN_VRowChanging != null)) {
                    this.AISTOCK_STOCK_TWO_PIN_VRowChanging(this, new AISTOCK_STOCK_TWO_PIN_VRowChangeEvent(((AISTOCK_STOCK_TWO_PIN_VRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.AISTOCK_STOCK_TWO_PIN_VRowDeleted != null)) {
                    this.AISTOCK_STOCK_TWO_PIN_VRowDeleted(this, new AISTOCK_STOCK_TWO_PIN_VRowChangeEvent(((AISTOCK_STOCK_TWO_PIN_VRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.AISTOCK_STOCK_TWO_PIN_VRowDeleting != null)) {
                    this.AISTOCK_STOCK_TWO_PIN_VRowDeleting(this, new AISTOCK_STOCK_TWO_PIN_VRowChangeEvent(((AISTOCK_STOCK_TWO_PIN_VRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveAISTOCK_STOCK_TWO_PIN_VRow(AISTOCK_STOCK_TWO_PIN_VRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                AISTOCK_STOCK_TWO_PIN_V_DATA ds = new AISTOCK_STOCK_TWO_PIN_V_DATA();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "AISTOCK_STOCK_TWO_PIN_VDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class AISTOCK_STOCK_TWO_PIN_VRow : global::System.Data.DataRow {
            
            private AISTOCK_STOCK_TWO_PIN_VDataTable tableAISTOCK_STOCK_TWO_PIN_V;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal AISTOCK_STOCK_TWO_PIN_VRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableAISTOCK_STOCK_TWO_PIN_V = ((AISTOCK_STOCK_TWO_PIN_VDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STOCK_CODE {
                get {
                    try {
                        return ((string)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“STOCK_CODE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string STOCK_NAME {
                get {
                    try {
                        return ((string)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“STOCK_NAME”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string YESTERDAY {
                get {
                    try {
                        return ((string)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“YESTERDAY”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal YESTERDAY_BEGIN {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_BEGINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“YESTERDAY_BEGIN”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_BEGINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal YESTERDAY_END {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_ENDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“YESTERDAY_END”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_ENDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal YESTERDAY_MIN_PRICE {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_MIN_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“YESTERDAY_MIN_PRICE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_MIN_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TODAY {
                get {
                    try {
                        return ((string)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“TODAY”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TODAY_BEGIN {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_BEGINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“TODAY_BEGIN”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_BEGINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TODAY_END {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_ENDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“TODAY_END”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_ENDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal TODAY_MIN_PRICE {
                get {
                    try {
                        return ((decimal)(this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_MIN_PRICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“AISTOCK_STOCK_TWO_PIN_V”中列“TODAY_MIN_PRICE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_MIN_PRICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTOCK_CODENull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTOCK_CODENull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsSTOCK_NAMENull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetSTOCK_NAMENull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.STOCK_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYESTERDAYNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYESTERDAYNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYESTERDAY_BEGINNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_BEGINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYESTERDAY_BEGINNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_BEGINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYESTERDAY_ENDNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_ENDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYESTERDAY_ENDNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_ENDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsYESTERDAY_MIN_PRICENull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_MIN_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetYESTERDAY_MIN_PRICENull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.YESTERDAY_MIN_PRICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTODAYNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.TODAYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTODAYNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTODAY_BEGINNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_BEGINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTODAY_BEGINNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_BEGINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTODAY_ENDNull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_ENDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTODAY_ENDNull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_ENDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTODAY_MIN_PRICENull() {
                return this.IsNull(this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_MIN_PRICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTODAY_MIN_PRICENull() {
                this[this.tableAISTOCK_STOCK_TWO_PIN_V.TODAY_MIN_PRICEColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class AISTOCK_STOCK_TWO_PIN_VRowChangeEvent : global::System.EventArgs {
            
            private AISTOCK_STOCK_TWO_PIN_VRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VRowChangeEvent(AISTOCK_STOCK_TWO_PIN_VRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public AISTOCK_STOCK_TWO_PIN_VRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591